---
name: Nginx Proxy Manager (Custom)
version: 1.0.0
slug: nginxproxymanager
description: Manage Nginx proxy hosts with a simple, powerful interface
url: https://github.com/johnaherninfotrack/hassio-addons/tree/main/addon-nginx-proxy-manager
codenotary: johnaherninfotrack
webui: http://[HOST]:[PORT:81]
init: false
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
ports:
  80/tcp: 80
  81/tcp: 81
  443/tcp: 443
map:
  - addon_config:rw
backup_exclude:
  - "*/logs"
